spring:
  application:
    name: kameleoon-trial-task
  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=user
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml